from app.api.central.prompt import system_prompt, user_query
from app.api.central.initializer import llm
from langchain_core.prompts import ChatPromptTemplate
from app.api.models.output import Reply
from langchain_core.output_parsers import PydanticOutputParser
from langchain.agents import create_tool_calling_agent, AgentExecutor
from app.api.services.tools import web_search, wiki_search
import markdown


async def reply_to_chat(query: str):

    parser = PydanticOutputParser(pydantic_object=Reply)

    prompt = ChatPromptTemplate.from_messages(
        [
            ("system", system_prompt),
            ("placeholder", "{chat_history}"),
            ("human", user_query),
            ("placeholder", "{agent_scratchpad}"),
        ]
    ).partial(format_instructions=parser.get_format_instructions())

    tools = [web_search, wiki_search]

    tool_agent = create_tool_calling_agent(
        llm=llm,
        tools=tools,
        prompt=prompt,
    )

    executor = AgentExecutor(
        agent=tool_agent,
        tools=tools,
        verbose=True,
        max_iterations=3,
        handle_parsing_errors=True,
    )

    raw_response = executor.invoke({"query": query})

    structured_response = parser.parse(raw_response.get("output"))  # type: ignore

    if structured_response.Title == "":
        output_str = f"<p>{structured_response.Response}</p>"
        return output_str

    try:
        Title_str = structured_response.Title
        Response_str = markdown.markdown(structured_response.Response)

        tlstr = ""

        if structured_response.tools_used:
            tools_used_str = ""
            sources_str = ""

            tools_used_str = ", ".join(structured_response.tools_used)
            sources_str = ",<br> ".join(structured_response.sources)

            tlstr = f"<br>Tools Used: <br><i>{tools_used_str}</i> <br><br>Sources: <br><i>{sources_str}</i> <br>"

        else:
            tlstr = "<br>Note: This response has been generated by the LLM model and may need additional verification."

        output_str = f"<h2>{Title_str}</h2> <br><p>{Response_str}</p> <br>{tlstr}"
        return output_str

    except Exception as e:
        output_str = f"error: {e}, parsing raw response: {raw_response}"
        print(output_str)
        return "Apologies, but our systems are momentarily busy. Please resubmit your request after few mminutes."
